use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

#[derive(Deserialize)]
struct BundleSpec {
    inputs: Vec<BundleSpecInput>,
}

#[derive(Deserialize)]
struct BundleSpecInput {
    label: String,
    archive: String,
}

#[derive(Deserialize)]
struct InstallConfig {
    artifacts: InstallArtifactLabels,
    platform: InstallPlatforms,
}

#[derive(Deserialize)]
struct InstallArtifactLabels {
    cli: String,
}

#[derive(Deserialize)]
struct InstallPlatforms {
    linux: InstallPlatformEntry,
    windows: InstallPlatformEntry,
}

#[derive(Deserialize)]
struct InstallPlatformEntry {
    base: String,
    cli: String,
    record: String,
}

fn main() {
    println!("cargo:rerun-if-env-changed=MZA_BUNDLE_INPUTS");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let generated_path = out_dir.join("mza_bundle_inputs.rs");

    // MZA_BUNDLE_INPUTS may be unset for a plain `cargo build`/`cargo check`
    // outside of MZA; fall back to no embedded inputs so the crate still compiles.
    let inputs = match env::var("MZA_BUNDLE_INPUTS") {
        Ok(spec_path) => read_inputs(Path::new(&spec_path), &out_dir),
        Err(_) => Vec::new(),
    };

    fs::write(&generated_path, render(&inputs))
        .unwrap_or_else(|err| panic!("Failed to write {}: {err}", generated_path.display()));

    generate_install_layout(&out_dir);

    // Cargo sets TARGET for build scripts; record it for the installation record.
    let target = env::var("TARGET").expect("TARGET is set by cargo for build scripts");
    println!("cargo:rustc-env=LEXICON_TARGET_TRIPLE={target}");
}

/// Reads `lexicon-install.toml` from the workspace root (found via `cargo
/// metadata`) and emits `$OUT_DIR/lexicon_install_layout.rs` with the
/// installer layout constants for the target being compiled for.
fn generate_install_layout(out_dir: &Path) {
    let workspace_root = locate_workspace_root();
    let config_path = workspace_root.join("lexicon-install.toml");
    println!("cargo:rerun-if-changed={}", config_path.display());

    let contents = fs::read_to_string(&config_path)
        .unwrap_or_else(|err| panic!("Failed to read {}: {err}", config_path.display()));
    let config: InstallConfig = toml::from_str(&contents)
        .unwrap_or_else(|err| panic!("Failed to parse {}: {err}", config_path.display()));

    let target_os = env::var("CARGO_CFG_TARGET_OS").expect("CARGO_CFG_TARGET_OS is set by cargo");
    let platform = match target_os.as_str() {
        "linux" => &config.platform.linux,
        "windows" => &config.platform.windows,
        other => panic!("lexicon-bundle/build.rs: unsupported CARGO_CFG_TARGET_OS \"{other}\""),
    };

    let generated = format!(
        "// Generated by lexicon-bundle/build.rs from lexicon-install.toml. Do not edit.\n\
         pub const CLI_ARTIFACT_LABEL: &str = \"{cli_label}\";\n\
         pub const INSTALL_BASE: &str = \"{base}\";\n\
         pub const CLI_INSTALL_PATH: &str = \"{cli_path}\";\n\
         pub const RECORD_INSTALL_PATH: &str = \"{record_path}\";\n",
        cli_label = config.artifacts.cli,
        base = platform.base,
        cli_path = platform.cli,
        record_path = platform.record,
    );

    let generated_path = out_dir.join("lexicon_install_layout.rs");
    fs::write(&generated_path, generated)
        .unwrap_or_else(|err| panic!("Failed to write {}: {err}", generated_path.display()));
}

fn locate_workspace_root() -> PathBuf {
    let output = Command::new("cargo")
        .args(["metadata", "--no-deps", "--format-version", "1"])
        .output()
        .unwrap_or_else(|err| panic!("Failed to run `cargo metadata`: {err}"));
    if !output.status.success() {
        panic!(
            "`cargo metadata` failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let metadata: serde_json::Value = serde_json::from_slice(&output.stdout)
        .unwrap_or_else(|err| panic!("Failed to parse `cargo metadata` output: {err}"));
    let workspace_root = metadata
        .get("workspace_root")
        .and_then(|value| value.as_str())
        .unwrap_or_else(|| panic!("`cargo metadata` output is missing \"workspace_root\""));
    PathBuf::from(workspace_root)
}

/// Copies each input archive into OUT_DIR and returns (label, OUT_DIR file name)
/// pairs, so the generated file's include_bytes! calls stay OUT_DIR-relative
/// rather than pointing at a build-host-only path.
fn read_inputs(spec_path: &Path, out_dir: &Path) -> Vec<(String, String)> {
    println!("cargo:rerun-if-changed={}", spec_path.display());
    let contents = fs::read_to_string(spec_path).unwrap_or_else(|err| {
        panic!(
            "Failed to read MZA_BUNDLE_INPUTS spec {}: {err}",
            spec_path.display()
        )
    });
    let spec: BundleSpec = toml::from_str(&contents).unwrap_or_else(|err| {
        panic!(
            "Failed to parse MZA_BUNDLE_INPUTS spec {}: {err}",
            spec_path.display()
        )
    });

    spec.inputs
        .into_iter()
        .map(|input| {
            let source = PathBuf::from(&input.archive);
            println!("cargo:rerun-if-changed={}", source.display());
            let file_name = source
                .file_name()
                .unwrap_or_else(|| panic!("Archive path {} has no file name", source.display()))
                .to_string_lossy()
                .into_owned();
            let dest = out_dir.join(&file_name);
            fs::copy(&source, &dest).unwrap_or_else(|err| {
                panic!(
                    "Failed to copy {} to {}: {err}",
                    source.display(),
                    dest.display()
                )
            });
            (input.label, file_name)
        })
        .collect()
}

fn render(inputs: &[(String, String)]) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by lexicon-bundle/build.rs from the MZA_BUNDLE_INPUTS spec. Do not edit.\n",
    );
    out.push_str("pub struct MzaBundleInput {\n    pub label: &'static str,\n    pub archive: &'static [u8],\n}\n\n");
    out.push_str("pub static MZA_BUNDLE_INPUTS: &[MzaBundleInput] = &[\n");
    for (label, file_name) in inputs {
        out.push_str(&format!(
            "    MzaBundleInput {{ label: \"{label}\", archive: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{file_name}\")) }},\n"
        ));
    }
    out.push_str("];\n");
    out
}
