use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct BundleSpec {
    inputs: Vec<BundleSpecInput>,
}

#[derive(Deserialize)]
struct BundleSpecInput {
    label: String,
    archive: String,
}

fn main() {
    println!("cargo:rerun-if-env-changed=MZA_BUNDLE_INPUTS");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let generated_path = out_dir.join("mza_bundle_inputs.rs");

    // MZA_BUNDLE_INPUTS may be unset for a plain `cargo build`/`cargo check`
    // outside of MZA; fall back to no embedded inputs so the crate still compiles.
    let inputs = match env::var("MZA_BUNDLE_INPUTS") {
        Ok(spec_path) => read_inputs(Path::new(&spec_path), &out_dir),
        Err(_) => Vec::new(),
    };

    fs::write(&generated_path, render(&inputs))
        .unwrap_or_else(|err| panic!("Failed to write {}: {err}", generated_path.display()));
}

/// Copies each input archive into OUT_DIR and returns (label, OUT_DIR file name)
/// pairs, so the generated file's include_bytes! calls stay OUT_DIR-relative
/// rather than pointing at a build-host-only path.
fn read_inputs(spec_path: &Path, out_dir: &Path) -> Vec<(String, String)> {
    println!("cargo:rerun-if-changed={}", spec_path.display());
    let contents = fs::read_to_string(spec_path)
        .unwrap_or_else(|err| panic!("Failed to read MZA_BUNDLE_INPUTS spec {}: {err}", spec_path.display()));
    let spec: BundleSpec = toml::from_str(&contents)
        .unwrap_or_else(|err| panic!("Failed to parse MZA_BUNDLE_INPUTS spec {}: {err}", spec_path.display()));

    spec.inputs
        .into_iter()
        .map(|input| {
            let source = PathBuf::from(&input.archive);
            println!("cargo:rerun-if-changed={}", source.display());
            let file_name = source
                .file_name()
                .unwrap_or_else(|| panic!("Archive path {} has no file name", source.display()))
                .to_string_lossy()
                .into_owned();
            let dest = out_dir.join(&file_name);
            fs::copy(&source, &dest)
                .unwrap_or_else(|err| panic!("Failed to copy {} to {}: {err}", source.display(), dest.display()));
            (input.label, file_name)
        })
        .collect()
}

fn render(inputs: &[(String, String)]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by lexicon-bundle/build.rs from the MZA_BUNDLE_INPUTS spec. Do not edit.\n");
    out.push_str("pub struct MzaBundleInput {\n    pub label: &'static str,\n    pub archive: &'static [u8],\n}\n\n");
    out.push_str("pub static MZA_BUNDLE_INPUTS: &[MzaBundleInput] = &[\n");
    for (label, file_name) in inputs {
        out.push_str(&format!(
            "    MzaBundleInput {{ label: \"{label}\", archive: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{file_name}\")) }},\n"
        ));
    }
    out.push_str("];\n");
    out
}
