use std::env;
use std::fs;
use std::path::{Component, Path, PathBuf};
use std::process::Command;

use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize)]
struct LexiconProjectConfig {
    schema_version: Option<u32>,
    project: Option<ProjectSection>,
}

#[derive(Debug, Serialize, Deserialize)]
struct SourceTomlDocument {
    schema_version: u32,
    source: SourceTomlSection,
}

#[derive(Debug, Serialize, Deserialize)]
struct SourceTomlSection {
    name: String,
    protocol: String,
}

#[derive(Debug, Deserialize)]
struct ProjectSection {
    name: Option<String>,
    sources_directory: Option<String>,
}

fn main() {
    let args: Vec<String> = env::args().skip(1).collect();

    if args.is_empty() {
        println!("lexicon-framework: no command given");
        return;
    }

    if args.len() == 1 && args[0] == "test" {
        println!("test::: installation successful and routed through the cli to the framework");
        return;
    }

    if args.len() == 3 && args[0] == "source" && args[1] == "new" {
        eprintln!("[lexicon] ERROR: 'source new' is not supported; use 'source create'");
        std::process::exit(1);
    }

    if args.len() == 5 && args[0] == "source" && args[1] == "build" && args[3] == "--protocol" {
        if let Err(error) = build_source(&args[2], &args[4]) {
            eprintln!("[lexicon] ERROR: {error}");
            std::process::exit(1);
        }
        return;
    }

    if args.len() == 4 && args[0] == "source" && args[1] == "build" {
        let protocol_flag = &args[3];
        if let Some(protocol) = protocol_flag.strip_prefix("--protocol=") {
            if let Err(error) = build_source(&args[2], protocol) {
                eprintln!("[lexicon] ERROR: {error}");
                std::process::exit(1);
            }
            return;
        }
    }

    if args.len() == 5 && args[0] == "source" && args[1] == "create" && args[3] == "--protocol" {
        if let Err(error) = generate_source_scaffold(&args[2], &args[4]) {
            eprintln!("[lexicon] ERROR: {error}");
            std::process::exit(1);
        }
        return;
    }

    if args.len() == 4 && args[0] == "source" && args[1] == "create" {
        let protocol_flag = &args[3];
        if let Some(protocol) = protocol_flag.strip_prefix("--protocol=") {
            if let Err(error) = generate_source_scaffold(&args[2], protocol) {
                eprintln!("[lexicon] ERROR: {error}");
                std::process::exit(1);
            }
            return;
        }
    }

    let joined = args.join(" ");
    eprintln!("[lexicon] ERROR: unknown command \"{joined}\"");
    std::process::exit(1);
}

fn generate_source_scaffold(source_name: &str, protocol: &str) -> Result<(), String> {
    validate_source_name(source_name)?;
    validate_protocol(protocol)?;

    let project_root = find_project_root(&env::current_dir().map_err(|error| {
        format!("failed to determine current directory: {error}")
    })?)?;
    let source_root = configured_sources_directory(&project_root)?;
    let source_dir = source_root.join(source_name);
    let protocol_dir = source_dir.join(protocol);

    if source_dir.exists() {
        return Err(format!(
            "source '{}' already exists at {}",
            source_name,
            source_dir.display()
        ));
    }

    fs::create_dir_all(&source_root).map_err(|error| {
        format!("failed to create {}: {error}", source_root.display())
    })?;

    let staging = tempfile::Builder::new()
        .prefix(&format!("{source_name}-"))
        .tempdir_in(&source_root)
        .map_err(|error| format!("failed to create staging directory in {}: {error}", source_root.display()))?;
    let staging_path = staging.path().to_path_buf();

    let directories = [
        Path::new("data/raw"),
        Path::new("data/processed"),
        Path::new("get-raw-data/sessions"),
        Path::new("get-raw-data/get-raw-data-impl/src"),
        Path::new("get-raw-data/runtime"),
        Path::new("process-data/sessions"),
        Path::new("process-data/process-data-impl/src"),
        Path::new("process-data/process-data-impl/processing"),
        Path::new("process-data/runtime"),
    ];

    for directory in &directories {
        let path = staging_path.join(directory);
        fs::create_dir_all(&path).map_err(|error| {
            format!("failed to create directory {}: {error}", path.display())
        })?;
    }

    let files = [
        ("source.toml", format_source_toml(source_name, protocol)),
        ("discovery.md", format_discovery_markdown(source_name)),
        (
            "data/raw/.gitkeep",
            "# generated by lexicon source create\n".to_string(),
        ),
        (
            "data/processed/.gitkeep",
            "# generated by lexicon source create\n".to_string(),
        ),
        (
            "get-raw-data/session_status.json",
            format_session_status_json(source_name, "get-raw-data"),
        ),
        (
            "process-data/session_status.json",
            format_session_status_json(source_name, "process-data"),
        ),
        (
            "get-raw-data/get-raw-data-impl/Cargo.toml",
            format_impl_cargo_toml(&format!("{source_name}-get-raw-data")),
        ),
        (
            "get-raw-data/get-raw-data-impl/Cargo.lock",
            format_cargo_lockfile(),
        ),
        (
            "get-raw-data/get-raw-data-impl/src/main.rs",
            format_get_raw_data_main(source_name),
        ),
        (
            "get-raw-data/runtime/.gitignore",
            "*\n!.gitignore\n".to_string(),
        ),
        (
            "process-data/process-data-impl/Cargo.toml",
            format_impl_cargo_toml(&format!("{source_name}-process-data")),
        ),
        (
            "process-data/process-data-impl/Cargo.lock",
            format_cargo_lockfile(),
        ),
        (
            "process-data/process-data-impl/src/main.rs",
            format_process_data_main(source_name),
        ),
        (
            "process-data/runtime/.gitignore",
            "*\n!.gitignore\n".to_string(),
        ),
    ];

    for (relative_path, contents) in &files {
        let path = staging_path.join(relative_path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).map_err(|error| {
                format!("failed to create parent directory for {}: {error}", path.display())
            })?;
        }
        fs::write(&path, contents).map_err(|error| {
            format!("failed to write {}: {error}", path.display())
        })?;
    }

    if let Err(error) = finalize_source_staging(staging, &protocol_dir) {
        return Err(error);
    }

    println!(
        "[lexicon] Created source '{}' using protocol '{}' at {}",
        source_name,
        protocol,
        protocol_dir.display()
    );
    println!("[lexicon] Files to edit next:");
    let output_files = [
        "source.toml",
        "discovery.md",
        "get-raw-data/get-raw-data-impl/src/main.rs",
        "process-data/process-data-impl/src/main.rs",
    ];
    for relative_path in &output_files {
        println!("[lexicon]   - {}", protocol_dir.join(relative_path).display());
    }

    Ok(())
}

fn build_source(source_name: &str, protocol: &str) -> Result<(), String> {
    validate_source_name(source_name)?;
    validate_protocol(protocol)?;

    let project_root = find_project_root(&env::current_dir().map_err(|error| {
        format!("failed to determine current directory: {error}")
    })?)?;
    let sources_root = configured_sources_directory(&project_root)?;
    let source_root = sources_root.join(source_name);
    let protocol_root = source_root.join(protocol);

    if !source_root.exists() {
        return Err(format!("source '{}' does not exist", source_name));
    }
    if !source_root.is_dir() {
        return Err(format!("source '{}' does not exist", source_name));
    }
    if !protocol_root.exists() {
        return Err(format!("protocol '{}' does not exist for source '{}'", protocol, source_name));
    }
    if !protocol_root.is_dir() {
        return Err(format!("protocol '{}' does not exist for source '{}'", protocol, source_name));
    }

    let source_toml = protocol_root.join("source.toml");
    let _source_doc = load_source_metadata(&source_toml, source_name, protocol)?;
    let get_manifest = protocol_root.join("get-raw-data/get-raw-data-impl/Cargo.toml");
    let process_manifest = protocol_root.join("process-data/process-data-impl/Cargo.toml");
    if !get_manifest.is_file() {
        return Err("missing get-raw-data implementation manifest".to_owned());
    }
    if !process_manifest.is_file() {
        return Err("missing process-data implementation manifest".to_owned());
    }

    let get_executable = build_single_crate(&get_manifest, "get-raw-data")?;
    let process_executable = build_single_crate(&process_manifest, "process-data")?;

    let get_runtime_dir = protocol_root.join("get-raw-data/runtime");
    let process_runtime_dir = protocol_root.join("process-data/runtime");
    fs::create_dir_all(&get_runtime_dir).map_err(|error| format!("failed to create {}: {error}", get_runtime_dir.display()))?;
    fs::create_dir_all(&process_runtime_dir).map_err(|error| format!("failed to create {}: {error}", process_runtime_dir.display()))?;

    let get_staged = stage_runtime_file(&get_runtime_dir, &get_executable, "get-raw-data")?;
    let process_staged = stage_runtime_file(&process_runtime_dir, &process_executable, "process-data")?;

    let mut get_backup = None;
    let mut process_backup = None;
    let get_final = get_runtime_dir.join(get_executable.file_name().unwrap().to_string_lossy().as_ref());
    let process_final = process_runtime_dir.join(process_executable.file_name().unwrap().to_string_lossy().as_ref());

    if get_final.exists() {
        get_backup = Some(move_to_backup(&get_final)?);
    }
    if process_final.exists() {
        process_backup = Some(move_to_backup(&process_final)?);
    }

    if let Err(error) = fs::rename(&get_staged, &get_final) {
        restore_runtime_after_failure(&get_final, get_backup.as_ref(), &get_staged, &process_staged, &process_final, process_backup.as_ref())?;
        return Err(format!("source runtime publication failed; previous runtimes were restored: {error}"));
    }
    if let Err(error) = fs::rename(&process_staged, &process_final) {
        let _ = fs::remove_file(&get_final);
        restore_runtime_after_failure(&get_final, get_backup.as_ref(), &get_staged, &process_staged, &process_final, process_backup.as_ref())?;
        return Err(format!("source runtime publication failed; previous runtimes were restored: {error}"));
    }

    if let Some(path) = get_backup.as_ref() {
        let _ = fs::remove_file(path);
    }
    if let Some(path) = process_backup.as_ref() {
        let _ = fs::remove_file(path);
    }

    println!("[lexicon] Built source '{}' using protocol '{}'", source_name, protocol);
    println!("[lexicon] Runtime executables:");
    println!("[lexicon]   - {}", get_final.canonicalize().unwrap_or_else(|_| get_final.clone()).display());
    println!("[lexicon]   - {}", process_final.canonicalize().unwrap_or_else(|_| process_final.clone()).display());
    Ok(())
}

fn load_source_metadata(path: &Path, expected_name: &str, expected_protocol: &str) -> Result<SourceTomlDocument, String> {
    if !path.is_file() {
        return Err("source metadata does not match the requested source and protocol".to_owned());
    }

    let contents = fs::read_to_string(path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    let parsed: SourceTomlDocument = toml::from_str(&contents)
        .map_err(|error| format!("failed to parse {}: {error}", path.display()))?;

    if parsed.schema_version != 1 {
        return Err("unsupported schema version".to_owned());
    }
    if parsed.source.name != expected_name {
        return Err("source metadata does not match the requested source and protocol".to_owned());
    }
    if parsed.source.protocol != expected_protocol {
        return Err("source metadata does not match the requested source and protocol".to_owned());
    }
    Ok(parsed)
}

fn build_single_crate(manifest_path: &Path, operation_name: &str) -> Result<PathBuf, String> {
    let manifest = manifest_path.canonicalize().map_err(|error| {
        format!("failed to resolve {}: {error}", manifest_path.display())
    })?;
    let tempdir = tempfile::Builder::new()
        .prefix(&format!("lexicon-{operation_name}-build-"))
        .tempdir()
        .map_err(|error| format!("failed to create temporary build directory: {error}"))?;
    let target_dir = tempdir.path().to_path_buf();

    let output = Command::new("cargo")
        .arg("build")
        .arg("--release")
        .arg("--locked")
        .arg("--manifest-path")
        .arg(&manifest)
        .arg("--target-dir")
        .arg(&target_dir)
        .arg("--message-format=json-render-diagnostics")
        .output()
        .map_err(|_| "[lexicon] ERROR: source build requires Cargo and a Rust development toolchain".to_owned())?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        if !stderr.trim().is_empty() {
            eprintln!("{stderr}");
        }
        return Err(format!("{} implementation build failed", operation_name));
    }

    let mut executable = None;
    for line in String::from_utf8_lossy(&output.stdout).lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() { continue; }
        if let Ok(value) = serde_json::from_str::<serde_json::Value>(trimmed) {
            if value.get("reason").and_then(|item| item.as_str()) == Some("compiler-artifact") {
                let target = value.get("target").and_then(|item| item.get("name")).and_then(|item| item.as_str());
                if let Some(target_name) = target {
                    let artifact = value.get("executable").and_then(|item| item.as_str());
                    if let Some(path) = artifact {
                        let candidate = PathBuf::from(path);
                        if candidate.is_file() && candidate.file_name().is_some() && !candidate.ends_with(".d") {
                            executable = Some(candidate);
                            if target_name.contains("main") || target_name.contains("get-raw-data") || target_name.contains("process-data") || target_name.contains("-impl") {
                                break;
                            }
                        }
                    }
                }
            }
        }
    }

    let executable = executable.ok_or_else(|| format!("{} implementation build failed", operation_name))?;
    if !executable.is_file() {
        return Err(format!("{} implementation build failed", operation_name));
    }

    let _ = tempdir.close();
    Ok(executable)
}

fn stage_runtime_file(runtime_dir: &Path, source_executable: &Path, operation_name: &str) -> Result<PathBuf, String> {
    let unique = format!(".{}.staging-{}", operation_name, std::process::id());
    let staged = runtime_dir.join(unique);
    fs::copy(source_executable, &staged).map_err(|error| {
        format!("failed to stage {}: {error}", runtime_dir.display())
    })?;
    let metadata = fs::metadata(&staged).map_err(|error| format!("failed to inspect staged {}: {error}", staged.display()))?;
    if !metadata.is_file() {
        let _ = fs::remove_file(&staged);
        return Err(format!("{} implementation build failed", operation_name));
    }
    Ok(staged)
}

fn move_to_backup(path: &Path) -> Result<PathBuf, String> {
    let unique = format!(".backup-{}-{}", std::process::id(), std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_nanos());
    let backup = path.parent().unwrap().join(unique);
    fs::rename(path, &backup).map_err(|error| format!("failed to create backup for {}: {error}", path.display()))?;
    Ok(backup)
}

fn restore_runtime_after_failure(
    get_final: &Path,
    get_backup: Option<&PathBuf>,
    get_staged: &Path,
    process_staged: &Path,
    process_final: &Path,
    process_backup: Option<&PathBuf>,
) -> Result<(), String> {
    let _ = fs::remove_file(get_staged);
    let _ = fs::remove_file(process_staged);
    let _ = fs::remove_file(get_final);
    let _ = fs::remove_file(process_final);
    if let Some(path) = get_backup {
        let restored = get_final;
        fs::rename(path, restored).map_err(|error| format!("failed to restore get runtime: {error}"))?;
    }
    if let Some(path) = process_backup {
        let restored = process_final;
        fs::rename(path, restored).map_err(|error| format!("failed to restore process runtime: {error}"))?;
    }
    Ok(())
}

fn finalize_source_staging(staging: tempfile::TempDir, source_dir: &Path) -> Result<(), String> {
    let staging_path = staging.path().to_path_buf();
    let source_parent = source_dir
        .parent()
        .ok_or_else(|| format!("failed to resolve parent directory for {}", source_dir.display()))?;

    if !source_parent.exists() {
        fs::create_dir_all(source_parent).map_err(|error| {
            format!("failed to create {}: {error}", source_parent.display())
        })?;
    }

    let rename_result = fs::rename(&staging_path, source_dir);

    if let Err(error) = rename_result {
        let _ = fs::remove_dir_all(&staging_path);
        let _ = fs::remove_dir(source_parent);
        drop(staging);
        return Err(format!(
            "failed to rename {} to {}: {error}",
            staging_path.display(),
            source_dir.display()
        ));
    }

    drop(staging);
    Ok(())
}

fn validate_source_name(source_name: &str) -> Result<(), String> {
    if source_name.trim().is_empty() {
        return Err("source name cannot be empty".to_string());
    }
    if source_name == "." || source_name == ".." {
        return Err(format!(
            "invalid source name '{}': use a simple source identifier",
            source_name
        ));
    }
    if Path::new(source_name).is_absolute() {
        return Err(format!(
            "invalid source name '{}': source names must be relative and not absolute",
            source_name
        ));
    }
    if source_name.contains(['/', '\\']) || source_name.split(['/', '\\']).any(|part| part.is_empty() || part == "." || part == "..") {
        return Err(format!(
            "invalid source name '{}': source names must be a single path segment",
            source_name
        ));
    }
    Ok(())
}

fn validate_protocol(protocol: &str) -> Result<(), String> {
    if protocol.eq_ignore_ascii_case("http") {
        Ok(())
    } else {
        Err(format!(
            "unsupported protocol '{}'; only 'http' is currently supported for source creation",
            protocol
        ))
    }
}

fn find_project_root(start_dir: &Path) -> Result<PathBuf, String> {
    let mut current = start_dir.to_path_buf();
    let mut ancestors = Vec::new();

    loop {
        let config_path = current.join("lexicon.toml");
        if config_path.is_file() {
            ancestors.push(current.clone());
        }

        match current.parent() {
            Some(parent) => current = parent.to_path_buf(),
            None => break,
        }
    }

    if ancestors.is_empty() {
        return Err("No Lexicon project found. The current directory is not inside a Lexicon project.".to_string());
    }

    if ancestors.len() > 1 {
        let outer = ancestors.last().cloned().expect("ancestor list should have outermost root");
        let nested = ancestors.first().cloned().expect("ancestor list should at least contain one project root");
        return Err(format!(
            "Nested Lexicon project detected.\nOuter project: {}\nNested project: {}\nMove the nested project outside the outer project, or remove its lexicon.toml if it should belong to the outer project, then rerun.\nNo changes were made.",
            outer.display(),
            nested.display()
        ));
    }

    let root = ancestors[0].clone();
    let descendant = find_descendant_project_root(&root)?;
    if let Some(nested_root) = descendant {
        return Err(format!(
            "Nested Lexicon project detected.\nOuter project: {}\nNested project: {}\nMove the nested project outside the outer project, or remove its lexicon.toml if it should belong to the outer project, then rerun.\nNo changes were made.",
            root.display(),
            nested_root.display()
        ));
    }

    Ok(root)
}

fn find_descendant_project_root(root: &Path) -> Result<Option<PathBuf>, String> {
    let mut found = None;
    visit_descendants(root, &mut found, root)?;
    Ok(found)
}

// Lexicon project roots are only legal under user-managed project trees. Generated and
// data-heavy directories are pruned before descendant discovery to avoid walking unbounded
// build or cache trees and to keep nested-root detection deterministic.
fn should_prune_descendant_directory(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|value| value.to_str()) else {
        return false;
    };

    if matches!(name, ".git" | "target" | "artifacts" | "bundles" | "mza") {
        return true;
    }

    if matches!(name, "raw" | "processed") {
        return path
            .parent()
            .and_then(Path::file_name)
            .and_then(|value| value.to_str())
            == Some("data");
    }

    false
}

fn visit_descendants(root: &Path, found: &mut Option<PathBuf>, current: &Path) -> Result<(), String> {
    let mut entries = fs::read_dir(current)
        .map_err(|error| format!("failed to read {}: {error}", current.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| format!("failed to read directory entry in {}: {error}", current.display()))?;
    entries.sort_by_key(|entry| entry.file_name());

    for entry in entries {
        let path = entry.path();

        if path.is_symlink() {
            continue;
        }

        if should_prune_descendant_directory(&path) {
            continue;
        }

        if path.is_dir() {
            let marker = path.join("lexicon.toml");
            if marker.is_file() && path != root {
                if found.is_none() {
                    *found = Some(path.clone());
                }
                return Ok(());
            }
            visit_descendants(root, found, &path)?;
            if found.is_some() {
                return Ok(());
            }
        }
    }

    Ok(())
}

fn resolve_project_directory(project_root: &Path, configured: &str) -> Result<PathBuf, String> {
    if configured.trim().is_empty() {
        return Err("sources_directory must not be empty".to_string());
    }

    let canonical_root = project_root
        .canonicalize()
        .map_err(|error| format!("failed to resolve project root: {error}"))?;

    let mut resolved = canonical_root.clone();
    for component in Path::new(configured).components() {
        match component {
            Component::Normal(name) => {
                let next = resolved.join(name);
                match fs::symlink_metadata(&next) {
                    Ok(metadata) if metadata.file_type().is_symlink() => {
                        let target = next.canonicalize().map_err(|error| {
                            format!("failed to resolve '{}': {error}", next.display())
                        })?;
                        if !target.starts_with(&canonical_root) {
                            return Err(format!(
                                "sources_directory '{}' escapes the project root",
                                configured
                            ));
                        }
                        resolved = target;
                    }
                    Ok(_) => {
                        resolved = next;
                    }
                    Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                        resolved = next;
                    }
                    Err(error) => {
                        return Err(format!(
                            "failed to inspect '{}': {error}",
                            next.display()
                        ));
                    }
                }
            }
            Component::CurDir => {}
            Component::ParentDir | Component::RootDir | Component::Prefix(_) => {
                return Err(format!(
                    "sources_directory '{}' must be a relative project path",
                    configured
                ));
            }
        }
    }

    if !resolved.starts_with(&canonical_root) {
        return Err(format!(
            "sources_directory '{}' escapes the project root",
            configured
        ));
    }
    if resolved.exists() && !resolved.is_dir() {
        return Err(format!(
            "sources_directory '{}' is not a directory",
            resolved.display()
        ));
    }
    Ok(resolved)
}

fn configured_sources_directory(project_root: &Path) -> Result<PathBuf, String> {
    let config_path = project_root.join("lexicon.toml");
    let contents = fs::read_to_string(&config_path)
        .map_err(|error| format!("failed to read {}: {error}", config_path.display()))?;
    let parsed: LexiconProjectConfig = toml::from_str(&contents)
        .map_err(|error| format!("failed to parse {}: {error}", config_path.display()))?;

    if parsed.schema_version != Some(1) {
        return Err(format!(
            "unsupported schema_version in {}: expected 1 but found {:?}",
            config_path.display(),
            parsed.schema_version
        ));
    }

    let project = parsed
        .project
        .as_ref()
        .ok_or_else(|| format!("missing [project] section in {}", config_path.display()))?;
    let project_name = project
        .name
        .as_deref()
        .ok_or_else(|| format!("missing project.name in {}", config_path.display()))?
        .trim();
    if project_name.is_empty() || project_name == "." || project_name == ".." || project_name.contains(['/', '\\']) {
        return Err(format!("invalid project.name '{}' in {}", project_name, config_path.display()));
    }

    let configured = project
        .sources_directory
        .as_deref()
        .unwrap_or("sources");

    let path = Path::new(configured);
    if path.is_absolute() {
        return Err(format!(
            "invalid sources_directory '{}' in {}: must be a relative path",
            configured,
            config_path.display()
        ));
    }
    if path.components().any(|component| matches!(component, Component::ParentDir | Component::RootDir | Component::Prefix(_))) {
        return Err(format!(
            "invalid sources_directory '{}' in {}: must remain within the project root",
            configured,
            config_path.display()
        ));
    }

    resolve_project_directory(project_root, configured)
}

fn format_source_toml(source_name: &str, protocol: &str) -> String {
    let document = SourceTomlDocument {
        schema_version: 1,
        source: SourceTomlSection {
            name: source_name.to_owned(),
            protocol: protocol.to_owned(),
        },
    };

    toml::to_string_pretty(&document)
        .unwrap_or_else(|error| panic!("failed to serialize source.toml: {error}"))
}

fn format_discovery_markdown(source_name: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {source_name}\n\n"));
    out.push_str("## Source description\n\n");
    out.push_str("Describe the source and the data it produces.\n\n");
    out.push_str("## Discovery method\n\n");
    out.push_str("Document how this source was discovered and why it belongs in this project.\n\n");
    out.push_str("## Acquisition endpoint or location\n\n");
    out.push_str("Record the upstream endpoint, dataset, or location used for acquisition.\n\n");
    out.push_str("## Why HTTP is the correct acquisition protocol\n\n");
    out.push_str("Explain why HTTP is the correct protocol for this source and how it matches the project contract.\n\n");
    out.push_str("## Required authentication or access conditions\n\n");
    out.push_str("List any required credentials, access restrictions, or network constraints.\n\n");
    out.push_str("## Attribution and usage notes\n\n");
    out.push_str("Capture attribution, licensing, and usage guidance for this source.\n\n");
    out.push_str("## Operational observations\n\n");
    out.push_str("Record operational notes, expected cadence, and troubleshooting observations.\n");
    out
}

fn format_impl_cargo_toml(package_name: &str) -> String {
    let mut out = String::new();
    out.push_str("[package]\n");
    out.push_str(&format!("name = \"{package_name}\"\n"));
    out.push_str("version = \"0.1.0\"\n");
    out.push_str("edition = \"2024\"\n\n");
    out.push_str("[dependencies]\n");
    out.push_str("lexicon-framework-core = {\n");
    out.push_str("    git = \"https://github.com/ssr2zvy/lexicon\",\n");
    out.push_str("    tag = \"v0.1.2\"\n");
    out.push_str("}\n");
    out
}

fn to_pascal_case(source_name: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = true;

    for ch in source_name.chars() {
        if ch == '-' || ch == '_' || ch == ' ' {
            capitalize_next = true;
            continue;
        }
        if capitalize_next {
            out.extend(ch.to_uppercase());
            capitalize_next = false;
        } else {
            out.extend(ch.to_lowercase());
        }
    }

    if out.is_empty() {
        "Source".to_string()
    } else {
        out
    }
}

fn format_get_raw_data_main(source_name: &str) -> String {
    let source_type = to_pascal_case(source_name);
    let mut out = String::new();
    out.push_str("use lexicon_framework_core::{\n");
    out.push_str("    run_http_source,\n");
    out.push_str("    HttpAcquisition,\n");
    out.push_str("    HttpAcquisitionContext,\n");
    out.push_str("};\n\n");
    out.push_str(&format!("struct {source_type};\n\n"));
    out.push_str(&format!("impl HttpAcquisition for {source_type} {{\n"));
    out.push_str(&format!(
        "    fn acquire(&self, context: &mut HttpAcquisitionContext) -> Result<(), String> {{\n"
    ));
    out.push_str("        let _ = context;\n");
    out.push_str("        todo!(\"implement HTTP acquisition\")\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("fn main() {\n");
    out.push_str(&format!("    let source = {source_type};\n"));
    out.push_str("    if let Err(error) = run_http_source(source) {\n");
    out.push_str("        eprintln!(\"[lexicon] ERROR: {error}\");\n");
    out.push_str("        std::process::exit(1);\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn format_process_data_main(source_name: &str) -> String {
    let mut out = String::new();
    out.push_str("fn main() {\n");
    out.push_str(&format!(
        "    println!(\"{source_name}: process-data scaffold is ready\");\n"
    ));
    out.push_str(
        "    println!(\"Edit the implementation to turn raw data into the source-specific SQLite dataset.\");\n",
    );
    out.push_str("}\n");
    out
}

fn format_cargo_lockfile() -> String {
    let mut out = String::new();
    out.push_str("# This file is automatically @generated by Cargo.\n");
    out.push_str("# It is not intended for manual editing.\n");
    out.push_str("version = 3\n");
    out
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::{
        configured_sources_directory, format_get_raw_data_main, format_impl_cargo_toml,
        format_source_toml, validate_protocol, validate_source_name,
    };

    #[test]
    fn generated_source_toml_matches_required_contract() {
        let source = format_source_toml("example-source", "http");

        assert!(source.contains("schema_version = 1"));
        assert!(source.contains("[source]"));
        assert!(source.contains("name = \"example-source\""));
        assert!(source.contains("protocol = \"http\""));
        assert!(!source.contains("id = \"example-source\""));
    }

    #[test]
    fn validate_source_name_and_protocol_require_safe_values() {
        assert!(validate_source_name("example-source").is_ok());
        assert!(validate_source_name("/bad").is_err());
        assert!(validate_source_name(".").is_err());
        assert!(validate_source_name("..").is_err());
        assert!(validate_protocol("http").is_ok());
        assert!(validate_protocol("browser").is_err());
    }

    #[test]
    fn generated_impl_manifest_uses_new_portable_core_tag() {
        let manifest = format_impl_cargo_toml("example-source-get-raw-data");

        assert!(manifest.contains("name = \"example-source-get-raw-data\""));
        assert!(manifest.contains("git = \"https://github.com/ssr2zvy/lexicon\""));
        assert!(manifest.contains("tag = \"v0.1.2\""));
        assert!(!manifest.contains("tag = \"v0.1.0\""));
        assert!(!manifest.contains("/workspaces/lexicon"));
    }

    #[test]
    fn generated_http_template_uses_context_based_acquire_contract() {
        let source = format_get_raw_data_main("example-source");

        assert!(source.contains("HttpAcquisitionContext"));
        assert!(source.contains("fn acquire(&self, context: &mut HttpAcquisitionContext)"));
        assert!(source.contains("if let Err(error) = run_http_source(source)"));
        assert!(source.contains("let source = ExampleSource;"));
    }

    #[test]
    fn configured_sources_directory_rejects_symlink_escape() {
        let root = std::env::temp_dir().join(format!("lexicon-sources-symlink-{}", std::process::id()));
        let outside = std::env::temp_dir().join(format!("lexicon-sources-outside-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        let _ = fs::remove_dir_all(&outside);
        fs::create_dir_all(&root).unwrap();
        fs::create_dir_all(&outside).unwrap();

        let symlink_path = root.join("sources");
        std::os::unix::fs::symlink(&outside, &symlink_path).unwrap();
        fs::write(root.join("lexicon.toml"), "schema_version = 1\n[project]\nname = \"demo\"\nsources_directory = \"sources\"\n").unwrap();

        let result = configured_sources_directory(&root);
        assert!(result.is_err(), "symlink escape should be rejected");

        let _ = fs::remove_dir_all(&root);
        let _ = fs::remove_dir_all(&outside);
    }

    #[test]
    fn configured_sources_directory_rejects_escaping_symlink_then_missing_child() {
        let root = std::env::temp_dir().join(format!("lexicon-sources-escape-child-{}", std::process::id()));
        let outside = std::env::temp_dir().join(format!("lexicon-sources-escape-outside-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        let _ = fs::remove_dir_all(&outside);
        fs::create_dir_all(&root).unwrap();
        fs::create_dir_all(&outside).unwrap();

        let link = root.join("link");
        std::os::unix::fs::symlink(&outside, &link).unwrap();
        fs::write(
            root.join("lexicon.toml"),
            "schema_version = 1\n[project]\nname = \"demo\"\nsources_directory = \"link/nonexistent-child\"\n",
        )
        .unwrap();

        let result = configured_sources_directory(&root);
        assert!(result.is_err(), "escaped symlink path with missing child should be rejected");

        let _ = fs::remove_dir_all(&root);
        let _ = fs::remove_dir_all(&outside);
    }

    #[test]
    fn find_project_root_rejects_descendant_nested_project() {
        let root = std::env::temp_dir().join(format!("lexicon-nested-root-{}", std::process::id()));
        let nested = root.join("tools/inner");
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&nested).unwrap();
        fs::write(root.join("lexicon.toml"), "schema_version = 1\n[project]\nname = \"outer\"\nsources_directory = \"sources\"\n").unwrap();
        fs::write(nested.join("lexicon.toml"), "schema_version = 1\n[project]\nname = \"inner\"\nsources_directory = \"sources\"\n").unwrap();

        let result = super::find_project_root(&root);
        assert!(result.is_err(), "nested descendant project should be rejected");
        let text = result.unwrap_err();
        assert!(text.contains("Outer project:"));
        assert!(text.contains("Nested project:"));

        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn find_descendant_project_root_prunes_excluded_directories() {
        let root = std::env::temp_dir().join(format!("lexicon-prune-root-{}", std::process::id()));
        let raw = root.join("data/raw");
        let processed = root.join("data/processed");
        let nested = root.join("data/nested-project");
        let _ = fs::remove_dir_all(&root);

        fs::create_dir_all(&raw).unwrap();
        fs::create_dir_all(&processed).unwrap();
        fs::create_dir_all(&nested).unwrap();

        fs::write(root.join("lexicon.toml"), "schema_version = 1\n[project]\nname = \"outer\"\nsources_directory = \"sources\"\n").unwrap();
        fs::write(raw.join("lexicon.toml"), "schema_version = 1\n[project]\nname = \"raw\"\nsources_directory = \"sources\"\n").unwrap();
        fs::write(processed.join("lexicon.toml"), "schema_version = 1\n[project]\nname = \"processed\"\nsources_directory = \"sources\"\n").unwrap();
        fs::write(nested.join("lexicon.toml"), "schema_version = 1\n[project]\nname = \"nested\"\nsources_directory = \"sources\"\n").unwrap();

        let result = super::find_descendant_project_root(&root).unwrap();
        assert_eq!(result, Some(nested), "data/raw and data/processed must be ignored while a real nested project under data/ is still detected");

        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn generated_discovery_markdown_contains_required_prompts() {
        let markdown = super::format_discovery_markdown("example-source");
        let required = [
            "# example-source",
            "## Source description",
            "Describe the source and the data it produces.",
            "## Discovery method",
            "Document how this source was discovered and why it belongs in this project.",
            "## Acquisition endpoint or location",
            "Record the upstream endpoint, dataset, or location used for acquisition.",
            "## Why HTTP is the correct acquisition protocol",
            "Explain why HTTP is the correct protocol for this source and how it matches the project contract.",
            "## Required authentication or access conditions",
            "List any required credentials, access restrictions, or network constraints.",
            "## Attribution and usage notes",
            "Capture attribution, licensing, and usage guidance for this source.",
            "## Operational observations",
            "Record operational notes, expected cadence, and troubleshooting observations.",
        ];

        for fragment in &required {
            assert!(markdown.contains(fragment), "discovery.md is missing required prompt: {fragment}\n---\n{markdown}");
        }
    }

    #[test]
    fn finalize_source_staging_cleans_up_tempdir_when_rename_fails() {
        let root = std::env::temp_dir().join(format!("lexicon-stage-cleanup-{}", std::process::id()));
        let sources_dir = root.join("sources");
        let source_dir = sources_dir.join("example-source");
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&sources_dir).unwrap();
        fs::write(root.join("lexicon.toml"), "schema_version = 1\n[project]\nname = \"demo\"\nsources_directory = \"sources\"\n").unwrap();

        let staging = tempfile::Builder::new()
            .prefix("example-source-")
            .tempdir_in(&sources_dir)
            .unwrap();
        let staging_path = staging.path().to_path_buf();
        fs::write(staging_path.join("source.toml"), "schema_version = 1\n").unwrap();
        fs::create_dir_all(&source_dir).unwrap();
        fs::write(source_dir.join("existing.txt"), "preserve-me\n").unwrap();

        let result = super::finalize_source_staging(staging, &source_dir);

        assert!(result.is_err(), "rename should fail when the final directory already exists");
        assert!(!staging_path.exists(), "staging directory must be removed on rename failure");
        assert!(source_dir.join("existing.txt").exists(), "existing content must remain untouched");

        let _ = fs::remove_dir_all(&root);
    }
}

fn format_session_status_json(source_name: &str, stage: &str) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str("  \"schema_version\": 1,\n");
    out.push_str(&format!("  \"source_id\": \"{source_name}\",\n"));
    out.push_str(&format!("  \"stage\": \"{stage}\",\n"));
    out.push_str("  \"status\": \"initialized\",\n");
    out.push_str("  \"last_updated\": null\n");
    out.push_str("}\n");
    out
}