use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

use serde::Deserialize;

#[derive(Deserialize)]
struct InstallConfig {
    platform: InstallPlatforms,
}

#[derive(Deserialize)]
struct InstallPlatforms {
    linux: InstallPlatformEntry,
    windows: InstallPlatformEntry,
}

#[derive(Deserialize)]
struct InstallPlatformEntry {
    cli: String,
    framework: String,
}

fn main() {
    let workspace_root = locate_workspace_root();
    let config_path = workspace_root.join("lexicon-install.toml");
    println!("cargo:rerun-if-changed={}", config_path.display());

    let contents = fs::read_to_string(&config_path)
        .unwrap_or_else(|err| panic!("Failed to read {}: {err}", config_path.display()));
    let config: InstallConfig = toml::from_str(&contents)
        .unwrap_or_else(|err| panic!("Failed to parse {}: {err}", config_path.display()));

    let target_os = env::var("CARGO_CFG_TARGET_OS").expect("CARGO_CFG_TARGET_OS is set by cargo");
    let platform = match target_os.as_str() {
        "linux" => &config.platform.linux,
        "windows" => &config.platform.windows,
        other => panic!("lexicon-cli/build.rs: unsupported CARGO_CFG_TARGET_OS \"{other}\""),
    };

    // The installed CLI's parent directory is its own "bin" folder; the
    // framework path recorded at compile time is relative to that folder.
    let cli_parent_segments = parent_segments(&platform.cli);
    let framework_segments = segments(&platform.framework);
    let relative = relative_path(&cli_parent_segments, &framework_segments);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let generated_path = out_dir.join("lexicon_runtime_layout.rs");
    let generated = format!(
        "// Generated by lexicon-cli/build.rs from lexicon-install.toml. Do not edit.\n\
         pub const FRAMEWORK_FROM_CLI: &str = \"{relative}\";\n"
    );
    fs::write(&generated_path, generated)
        .unwrap_or_else(|err| panic!("Failed to write {}: {err}", generated_path.display()));
}

fn segments(path: &str) -> Vec<&str> {
    path.split(['/', '\\']).filter(|segment| !segment.is_empty()).collect()
}

fn parent_segments(path: &str) -> Vec<&str> {
    let mut segments = segments(path);
    segments.pop();
    segments
}

/// Computes the relative path from `from_dir` (a directory) to `to` (a file),
/// both expressed as path segments relative to the same base directory.
fn relative_path(from_dir: &[&str], to: &[&str]) -> String {
    let common = from_dir.iter().zip(to.iter()).take_while(|(a, b)| a == b).count();

    let mut parts: Vec<&str> = Vec::new();
    for _ in common..from_dir.len() {
        parts.push("..");
    }
    parts.extend_from_slice(&to[common..]);
    parts.join("/")
}

fn locate_workspace_root() -> PathBuf {
    let output = Command::new("cargo")
        .args(["metadata", "--no-deps", "--format-version", "1"])
        .output()
        .unwrap_or_else(|err| panic!("Failed to run `cargo metadata`: {err}"));
    if !output.status.success() {
        panic!(
            "`cargo metadata` failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let metadata: serde_json::Value = serde_json::from_slice(&output.stdout)
        .unwrap_or_else(|err| panic!("Failed to parse `cargo metadata` output: {err}"));
    let workspace_root = metadata
        .get("workspace_root")
        .and_then(|value| value.as_str())
        .unwrap_or_else(|| panic!("`cargo metadata` output is missing \"workspace_root\""));
    PathBuf::from(workspace_root)
}
